"""
QuantMind Core Types
====================
Shared type definitions used across all modules. These are the fundamental
data structures that flow through the system.

Design Principle: Use Python dataclasses for lightweight value objects and
Pydantic models for validated configurations. Enums enforce type safety
for categorical values.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional

import numpy as np
import pandas as pd


# ============================================================
# Enums
# ============================================================


class Timeframe(str, enum.Enum):
    """Supported OHLCV timeframes."""
    M1 = "1m"
    M5 = "5m"
    M15 = "15m"
    M30 = "30m"
    H1 = "1h"
    H4 = "4h"
    D1 = "1d"
    W1 = "1w"

    @property
    def minutes(self) -> int:
        """Return the timeframe duration in minutes."""
        mapping = {
            "1m": 1, "5m": 5, "15m": 15, "30m": 30,
            "1h": 60, "4h": 240, "1d": 1440, "1w": 10080,
        }
        return mapping[self.value]


class Side(str, enum.Enum):
    """Trade side."""
    BUY = "buy"
    SELL = "sell"


class OrderType(str, enum.Enum):
    """Order type."""
    MARKET = "market"
    LIMIT = "limit"
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    STOP_LIMIT = "stop_limit"


class OrderStatus(str, enum.Enum):
    """Order lifecycle status."""
    PENDING = "pending"
    SUBMITTED = "submitted"
    PARTIAL = "partial"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class SignalType(str, enum.Enum):
    """Trading signal types."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    INCREASE = "increase"
    DECREASE = "decrease"


class Regime(str, enum.Enum):
    """Market regime labels from clustering/HMM."""
    TRENDING_UP = "trending_up"
    TRENDING_DOWN = "trending_down"
    MEAN_REVERTING = "mean_reverting"
    HIGH_VOLATILITY = "high_volatility"
    LOW_VOLATILITY = "low_volatility"
    UNKNOWN = "unknown"


class DataSource(str, enum.Enum):
    """Supported data providers."""
    BINANCE = "binance"
    YAHOO = "yahoo"
    CRYPTO_COMPARE = "crypto_compare"
    FEAR_GREED = "fear_greed"
    POLYGON = "polygon"


# ============================================================
# Data Structures
# ============================================================


@dataclass(frozen=True)
class OHLCV:
    """Single OHLCV bar."""
    timestamp: datetime
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    source: DataSource = DataSource.BINANCE
    timeframe: Timeframe = Timeframe.D1

    def to_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "symbol": self.symbol,
            "open": self.open,
            "high": self.high,
            "low": self.low,
            "close": self.close,
            "volume": self.volume,
            "source": self.source.value,
            "timeframe": self.timeframe.value,
        }


@dataclass
class Signal:
    """Trading signal generated by a model or strategy."""
    timestamp: datetime
    symbol: str
    signal_type: SignalType
    confidence: float  # 0.0 to 1.0
    model_name: str
    features_used: list[str] = field(default_factory=list)
    explanation: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class Order:
    """An order to be submitted to the broker."""
    id: str
    timestamp: datetime
    symbol: str
    side: Side
    order_type: OrderType
    quantity: float
    price: Optional[float] = None  # None for market orders
    stop_price: Optional[float] = None
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: float = 0.0
    filled_price: float = 0.0
    commission: float = 0.0
    latency_ms: float = 0.0
    signal: Optional[Signal] = None  # The signal that triggered this order
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class Position:
    """Current position in a symbol."""
    symbol: str
    side: Side
    quantity: float
    entry_price: float
    current_price: float
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    opened_at: Optional[datetime] = None

    @property
    def market_value(self) -> float:
        return self.quantity * self.current_price

    @property
    def cost_basis(self) -> float:
        return self.quantity * self.entry_price

    @property
    def return_pct(self) -> float:
        if self.entry_price == 0:
            return 0.0
        direction = 1.0 if self.side == Side.BUY else -1.0
        return direction * (self.current_price - self.entry_price) / self.entry_price


@dataclass
class Trade:
    """A completed trade (entry + exit)."""
    id: str
    symbol: str
    side: Side
    entry_price: float
    exit_price: float
    quantity: float
    entry_time: datetime
    exit_time: datetime
    pnl: float
    pnl_pct: float
    commission: float
    slippage: float
    holding_period_minutes: int
    signal: Optional[Signal] = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class PortfolioState:
    """Snapshot of the portfolio at a point in time."""
    timestamp: datetime
    equity: float
    cash: float
    positions: list[Position] = field(default_factory=list)
    open_orders: list[Order] = field(default_factory=list)
    total_pnl: float = 0.0
    total_commission: float = 0.0
    drawdown: float = 0.0
    max_drawdown: float = 0.0
    sharpe_ratio: float = 0.0
    sortino_ratio: float = 0.0

    @property
    def position_count(self) -> int:
        return len(self.positions)

    @property
    def total_exposure(self) -> float:
        return sum(abs(p.market_value) for p in self.positions)

    @property
    def leverage(self) -> float:
        if self.equity == 0:
            return 0.0
        return self.total_exposure / self.equity


# ============================================================
# Feature Types
# ============================================================


@dataclass
class FeatureDefinition:
    """Metadata about a computed feature."""
    name: str
    group: str  # e.g., "technical", "statistical", "microstructure"
    description: str
    params: dict[str, Any] = field(default_factory=dict)
    dependencies: list[str] = field(default_factory=list)  # OHLCV columns needed


@dataclass
class FeatureSet:
    """A named collection of features with their data."""
    name: str
    version: str
    symbol: str
    timeframe: Timeframe
    features: pd.DataFrame  # columns = feature names, index = timestamps
    definitions: list[FeatureDefinition] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)

    @property
    def feature_names(self) -> list[str]:
        return list(self.features.columns)

    @property
    def num_features(self) -> int:
        return len(self.features.columns)

    @property
    def num_samples(self) -> int:
        return len(self.features)


# ============================================================
# Backtest Types
# ============================================================


@dataclass
class BacktestResult:
    """Results from a backtest run."""
    strategy_name: str
    symbol: str
    timeframe: Timeframe
    start_date: datetime
    end_date: datetime
    initial_capital: float
    final_equity: float
    total_return: float
    sharpe_ratio: float
    sortino_ratio: float
    calmar_ratio: float
    max_drawdown: float
    max_drawdown_duration_days: int
    win_rate: float
    profit_factor: float
    total_trades: int
    avg_trade_pnl: float
    avg_holding_period_minutes: float
    total_commission: float
    total_slippage: float
    equity_curve: Optional[pd.Series] = None
    trades: list[Trade] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class FeatureDefinition:
    """Metadata about a registered feature."""
    name: str
    group: str = "custom"
    description: str = ""
    params: dict[str, Any] = field(default_factory=dict)
    dependencies: list[str] = field(default_factory=lambda: ["close"])

